language: android 
jdk: 
  - oraclejdk8 
android: 
  components: 
    - tools 
    - build-tools-26.0.1 
    - android-26 
    - Extra-android-support 
    - extra-google-google_play_services 
    - extra-android-m2repository 
    - extra-google-m2repository 
    - addon-google_apis-google-24 
BEFORE_INSTALL: 
- ​​chmod +x gradlew 
- export JAVA8_HOME = / usr / lib / jvm / java-8-oracle 
- export JAVA_HOME = $ JAVA8_HOME 

script: 
- ./gradlew build

deploy:
  - provider: releases
    api_key: "$GITHUB_API_KEY"
    file: app/build/outputs/apk/*
    file_glob: true
    skip_cleanup: true
    on:
        tags: true
        branch: master
